export const types = {
  SET_USER: 'SET_USER',
  SET_USER_LOCATION: 'SET_USER_LOCATION',
  SET_TOKEN: 'SET_TOKEN',
  SET_DECLARATION: 'SET_DECLARATION',
  SET_HEALTHCHECK: 'SET_HEALTHCHECK',
  SET_LOGOUT: 'SET_LOGOUT',
  SET_DONATION: 'SET_DONATION',
  SET_DONATION_LIST: 'SET_DONATION_LIST',
  SET_PHOTO_RECEIVED: 'SET_PHOTO_RECEIVED',
  SET_CARD_LIST: 'SET_CARD_LIST',
  CLEAN_USER_INFO: 'CLEAN_USER_INFO',
}
